### PR TITLE
Partial documentation clean up, moved plugin

### PR DESCRIPTION
**Pull request by kuklinistvan**

### CODE REVIEW

**Comment by AntonOfTheWoods** [comment]
Thanks for this @kuklinistvan . I may be being a little picky here but do we really need capital letters for the beginning of the file names? I guess I am used to python naming, where you have either all caps or no caps, and underscores between words. I am Ok to merge this if you can get a vote from someone else, like @VikashKothary. Is that Ok?

**Comment by kuklinistvan** [comment]
It was a decision made by tossing a coin, of course it is okay to rename the files to low-caps :)

**Comment by VikashKothary** [comment]
Lol my feedback will be equally nitpicky 😇 I feel like it was already called that. But can we call it `docs` over `doc`?

**Comment by AntonOfTheWoods** [comment]
So unless I'm mistaken these changes have already been merged in another PR, closing

**Pull request closed without merging**
